version: "3.8"
services:
  db:
    image: "postgres:15-alpine"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: ./.env

volumes:
  pgdata:
