from punq import Container

from .domain.protocols.repositories import LearningCourseRepository, RegionalOrganizationRepository
from .domain.protocols.translators import DisabilityGroupTranslator, TrainingLevelTranslator
from .domain.protocols.usecases import GetCourseFoldersUsecase, GetRequestFormOptionsUsecase
from .infrastructure.repositories import LearningCourseDjangoRepository, RegionalOrganizationDjangoRepository
from .infrastructure.translators import DisabilityGroupDjangoTranslator, TrainingLevelDjangoTranslator
from .services import GetCourseFoldersService, GetRequestFormOptionsService


course_folders_container = Container()
course_folders_container.register(LearningCourseRepository, LearningCourseDjangoRepository)
course_folders_container.register(GetCourseFoldersUsecase, GetCourseFoldersService)


request_form_options_container = Container()
request_form_options_container.register(LearningCourseRepository, LearningCourseDjangoRepository)
request_form_options_container.register(RegionalOrganizationRepository, RegionalOrganizationDjangoRepository)
request_form_options_container.register(DisabilityGroupTranslator, DisabilityGroupDjangoTranslator)
request_form_options_container.register(TrainingLevelTranslator, TrainingLevelDjangoTranslator)
request_form_options_container.register(GetRequestFormOptionsUsecase, GetRequestFormOptionsService)
