from punq import Container

from .domain.protocols.repositories import LearningCourseRepository, RegionalOrganizationRepository
from .domain.protocols.translators import DisabilityGroupTranslator, TrainingLevelTranslator
from .domain.protocols.usecases import GetCourseListUsecase, GetRequestFormOptionsUsecase
from .infrastructure.repositories import LearningCourseDjangoRepository, RegionalOrganizationDjangoRepository
from .infrastructure.translators import DisabilityGroupDjangoTranslator, TrainingLevelDjangoTranslator
from .services import GetCourseListService, GetRequestFormOptionsService


course_list_container = Container()
course_list_container.register(LearningCourseRepository, LearningCourseDjangoRepository)
course_list_container.register(GetCourseListUsecase, GetCourseListService)


request_form_options_container = Container()
request_form_options_container.register(LearningCourseRepository, LearningCourseDjangoRepository)
request_form_options_container.register(RegionalOrganizationRepository, RegionalOrganizationDjangoRepository)
request_form_options_container.register(DisabilityGroupTranslator, DisabilityGroupDjangoTranslator)
request_form_options_container.register(TrainingLevelTranslator, TrainingLevelDjangoTranslator)
request_form_options_container.register(GetRequestFormOptionsUsecase, GetRequestFormOptionsService)
