from logging import getLogger, Logger

from punq import Container
from server.common.protocols import HttpController

from .domain.protocols.repositories import LearningCourseRepository, RegionalOrganizationRepository
from .domain.protocols.translators import DisabilityGroupTranslator, TrainingLevelTranslator
from .domain.protocols.usecases import GetCourseFoldersUsecase, GetRequestFormOptionsUsecase
from .infrastructure.repositories import LearningCourseDjangoRepository, RegionalOrganizationDjangoRepository
from .infrastructure.translators import DisabilityGroupDjangoTranslator, TrainingLevelDjangoTranslator
from .services import GetCourseFoldersService, GetRequestFormOptionsService
from .views import AddLearningRequestView, GetFoldersListView


# Common object for logging on all business services
_logger_object = getLogger(__name__)

folder_list_service_impl = Container()
folder_list_service_impl.register(Logger, instance=_logger_object)
folder_list_service_impl.register(LearningCourseRepository, LearningCourseDjangoRepository)
folder_list_service_impl.register(GetCourseFoldersUsecase, GetCourseFoldersService)
folder_list_service_impl.register(HttpController, GetFoldersListView)


add_learning_request_impl = Container()
add_learning_request_impl.register(Logger, instance=_logger_object)
add_learning_request_impl.register(LearningCourseRepository, LearningCourseDjangoRepository)
add_learning_request_impl.register(RegionalOrganizationRepository, RegionalOrganizationDjangoRepository)
add_learning_request_impl.register(DisabilityGroupTranslator, DisabilityGroupDjangoTranslator)
add_learning_request_impl.register(TrainingLevelTranslator, TrainingLevelDjangoTranslator)
add_learning_request_impl.register(GetRequestFormOptionsUsecase, GetRequestFormOptionsService)
add_learning_request_impl.register(HttpController, AddLearningRequestView)
